export default {
  '0ad6c4c1': [() => import(/* webpackChunkName: '0ad6c4c1' */ "@site/docs/update/update1.2.2.md"), "@site/docs/update/update1.2.2.md", require.resolveWeak("@site/docs/update/update1.2.2.md")],
  '0cda6715': [() => import(/* webpackChunkName: '0cda6715' */ "@site/docs/particle/useParticle.md"), "@site/docs/particle/useParticle.md", require.resolveWeak("@site/docs/particle/useParticle.md")],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  '293fda69': [() => import(/* webpackChunkName: '293fda69' */ "@site/docs/api/particle.GravityParticle.md"), "@site/docs/api/particle.GravityParticle.md", require.resolveWeak("@site/docs/api/particle.GravityParticle.md")],
  '2fb8647b': [() => import(/* webpackChunkName: '2fb8647b' */ "@site/src/pages/Main.js"), "@site/src/pages/Main.js", require.resolveWeak("@site/src/pages/Main.js")],
  '390319b5': [() => import(/* webpackChunkName: '390319b5' */ "@site/docs/particle/introduction.md"), "@site/docs/particle/introduction.md", require.resolveWeak("@site/docs/particle/introduction.md")],
  '5e837002': [() => import(/* webpackChunkName: '5e837002' */ "@site/docs/api/particle.Particle.md"), "@site/docs/api/particle.Particle.md", require.resolveWeak("@site/docs/api/particle.Particle.md")],
  '65c94ed6': [() => import(/* webpackChunkName: '65c94ed6' */ "~docs/testdoc-docs-route-529.json"), "~docs/testdoc-docs-route-529.json", require.resolveWeak("~docs/testdoc-docs-route-529.json")],
  '7166129b': [() => import(/* webpackChunkName: '7166129b' */ "@site/docs/api/global.Types.md"), "@site/docs/api/global.Types.md", require.resolveWeak("@site/docs/api/global.Types.md")],
  '90e2d20f': [() => import(/* webpackChunkName: '90e2d20f' */ "@site/docs/particle/GravityParticleSystem.md"), "@site/docs/particle/GravityParticleSystem.md", require.resolveWeak("@site/docs/particle/GravityParticleSystem.md")],
  '94439cc6': [() => import(/* webpackChunkName: '94439cc6' */ "@site/docs/particle/ParticleSystem.md"), "@site/docs/particle/ParticleSystem.md", require.resolveWeak("@site/docs/particle/ParticleSystem.md")],
  '9a97fb2b': [() => import(/* webpackChunkName: '9a97fb2b' */ "@site/docs/api/particle.ParticleSystem.md"), "@site/docs/api/particle.ParticleSystem.md", require.resolveWeak("@site/docs/api/particle.ParticleSystem.md")],
  '9b96d9e3': [() => import(/* webpackChunkName: '9b96d9e3' */ "@site/docs/manual/manual.md"), "@site/docs/manual/manual.md", require.resolveWeak("@site/docs/manual/manual.md")],
  'a2665b94': [() => import(/* webpackChunkName: 'a2665b94' */ "@site/docs/particle/ParticleExtensions.md"), "@site/docs/particle/ParticleExtensions.md", require.resolveWeak("@site/docs/particle/ParticleExtensions.md")],
  'b756a1c0': [() => import(/* webpackChunkName: 'b756a1c0' */ "@site/docs/api/particle.GravityParticleSystem.md"), "@site/docs/api/particle.GravityParticleSystem.md", require.resolveWeak("@site/docs/api/particle.GravityParticleSystem.md")],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],};
